apiVersion: v1
kind: Secret
metadata:
  name: school-db-secret
type: Opaque
stringData:
  MONGODB_URI: "mongodb://admin:password123@mongodb-service:27017/schooldb?authSource=admin"
data:
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQxMjM=
