upstream frontend {
    server frontend:3000;

}

upstream studentservice {
    server studentservice:5001;
}
upstream teacherservice {
    server teacherservice:5002;
}
upstream employeeservice {
    server employeeservice:5003;
}

server {

    location /studentservice/ {
       proxy_pass http://studentservice/;
   }
    location /teacherservice/ {
       proxy_pass http://teacherservice/;
   }
    location /employeeservice {
       proxy_pass http://employeeservice/;
   }
   
    location / {
        proxy_pass http://frontend;
    }


}
